version: '2'
services:
  server:
    image: consul:0.7.5
    network_mode: host
    restart: always
    command: consul agent -server --data-dir=/consul/data -bootstrap-expect=${BOOTSTRAP_EXPECT} -bind=${LOCAL_IP} -ui -client=0.0.0.0 -advertise=${LOCAL_IP} -join=${MASTER0_IP}  -join=${MASTER1_IP} -join=${MASTER2_IP}
    volumes:
      - server-data:/consul/data
  agent:
    image: consul:0.7.5
    network_mode: host
    restart: always
    command:  consul agent -data-dir=/consul/data -advertise=${LOCAL_IP}  -bind=${LOCAL_IP} -join=${MASTER0_IP}  -join=${MASTER1_IP} -join=${MASTER2_IP} -client=0.0.0.0 -ui
    volumes:
      - agent-data:/consul/data
  mesos-consul:
    image: ciscocloud/mesos-consul:v0.4.0
    network_mode: host
    restart: always
    command: --zk=${ZK_URL}/mesos --consul
volumes:
  server-data:
  agent-data: